# Configuration Alternative : Pipeline avec MongoDB (tous les tests)
# Remplacez le contenu de .github/workflows/devops.yml par celui-ci si vous voulez exécuter tous les 23 tests

name: CI/CD Pipeline - Backend Suivi Processus Qualité

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  # Job 1: Build et Test
  build-and-test:
    name: Build et Test Backend
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: testuser
          MONGO_INITDB_ROOT_PASSWORD: testpass
          MONGO_INITDB_DATABASE: test
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ping: 1})' --quiet"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Vérification de la version Java
        run: java -version
      
      - name: Donner les permissions au Maven Wrapper
        run: chmod +x mvnw
      
      - name: Build avec Maven
        run: ./mvnw clean install -DskipTests
      
      - name: Créer un fichier de configuration de test
        run: |
          mkdir -p src/test/resources
          cat > src/test/resources/application-test.properties << EOF
          spring.data.mongodb.uri=mongodb://testuser:testpass@localhost:27017/test?authSource=admin
          spring.data.mongodb.database=test
          EOF
      
      - name: Exécution des tests unitaires
        env:
          SPRING_PROFILES_ACTIVE: test
          SPRING_DATA_MONGODB_URI: mongodb://testuser:testpass@localhost:27017/test?authSource=admin
        run: ./mvnw test
      
      - name: Génération du rapport de couverture
        run: ./mvnw jacoco:report
        continue-on-error: true
      
      - name: Upload des artefacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: target/*.jar
          retention-days: 7

  # Job 2: Analyse de code avec SonarQube (optionnel)
  code-quality:
    name: Analyse de qualité du code
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Configuration Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Donner les permissions au Maven Wrapper
        run: chmod +x mvnw
      
      - name: Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw clean verify sonar:sonar \
            -Dsonar.projectKey=suivi-processus-qualite \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
        continue-on-error: true

  # Job 3: Build Docker Image
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Configuration Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      - name: Donner les permissions au Maven Wrapper
        run: chmod +x mvnw
      
      - name: Build du projet
        run: ./mvnw clean package -DskipTests
      
      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build et Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/suivi-qualite-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/suivi-qualite-backend:${{ github.sha }}

  # Job 4: Déploiement (optionnel)
  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      
      - name: Déploiement sur le serveur
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /opt/suivi-qualite
            docker-compose pull backend
            docker-compose up -d backend
            docker system prune -f

  # Job 5: Notification
  notify:
    name: Notification
    runs-on: ubuntu-latest
    needs: [build-and-test, code-quality, docker-build, deploy]
    if: always()
    
    steps:
      - name: Notification de succès
        if: success()
        run: |
          echo "✅ Pipeline CI/CD exécuté avec succès!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
      
      - name: Notification d'échec
        if: failure()
        run: |
          echo "❌ Échec du pipeline CI/CD"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
